language: python
dist: xenial

cache:
  paths:
    - .venv
  key: "${CI_COMMIT_REF_SLUG}"

sudo: false

addons:
    apt:
        packages:
            - texlive
            - texlive-full
            - dvipng
            - graphviz
            - pandoc

env:
  matrix:
    - BUILD_CMD='html'
    - BUILD_CMD='latexpdf'
            
python:
    - 3.7

before_install:
  - pip install poetry

script:
    - poetry config settings.virtualenvs.in-project true
    - poetry install
    - mkdir -p _build/latex/
    - bash get_newfloat.sty.sh ./_build/latex/
    - poetry run make $BUILD_CMD
