[build]
publish = "_build/html/"
command = """
restore_home_cache ".cache" "pip cache" && \
restore_cwd_cache '.venv' 'python virtualenv' && \
python3 -m pip install -q poetry && \
poetry config settings.virtualenvs.in-project true && \
poetry install && \
poetry run make html
"""
